ServerName localhost
Listen __PORT__

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

TypesConfig /etc/apache2/mime.types
DirectoryIndex index.php index.html

ErrorLog /dev/stderr
TransferLog /dev/stdout
LogLevel warn

DocumentRoot /app/public

<Directory /app/public>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch "\.php$">
    SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>
